apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cidr-example
spec:
  compositeTypeRef:
    apiVersion: platform.upbound.io/v1alpha1
    kind: XVPC
  mode: Pipeline
  pipeline:
  - step: cidr
    functionRef:
      name: function-cidr
    input:
      apiVersion: cidr.fn.crossplane.io/v1beta1
      kind: Parameters
      cidrFunc: cidrhost
      prefixField: "spec.forFunction.cidrBlock"
      hostNumField: "spec.forFunction.hostNum"
      outputField: "status.atFunction.cidr.hostAddress"
