apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcidrs.platform.upbound.io
  labels:
    platform.upbound.io/function: cidr
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: platform.upbound.io/v1alpha1
    kind: XCIDR
  patchSets:
    - name: common-parameters
      patches:
        - fromFieldPath: spec.parameters.providerConfig
          toFieldPath: spec.providerConfigRef.name
        - fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.forProvider.deletionPolicy
        - fromFieldPath: spec.parameters.providerConfig
          toFieldPath: spec.forProvider.providerConfigRef.name
    - name: for-cidr-function
      patches:
        - fromFieldPath: spec.parameters.cidrFunc
          toFieldPath: spec.cidrFunc
        - fromFieldPath: spec.parameters.prefix
          toFieldPath: spec.prefix
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.parameters.newBits
          toFieldPath: spec.newBits
        - fromFieldPath: spec.parameters.netNum
          toFieldPath: spec.netNum
  resources:
    - name: subnet
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        spec:
          forProvider:
            availabilityZone:
            cidrBlock: # "192.0.0.0/22"
            region:
            tags:
              Owner: "Platform Team"
              Name: "subnet"
              kubernetes.io/role/internal-elb: "1"
            vpcIdRef:
              name:
            vpcIdSelector:
              matchControllerRef: true
            providerConfigRef:
              name:
          forFunction:
            cidrFunc: cidrsubnet
      patches:
        - type: PatchSet
          patchSetName: common-parameters
        - type: PatchSet
          patchSetName: for-cidr-function
